### ISSUE TITLE
Error in Question no. 4

### ISSUE THREAD

**Issue by vatsar** [vatsar/Bioinformatics-Project#1]
The M in the mean should be capital, same as in the last Question but it is in small letter by mistake in this one.

**Comment by gulnoorkaur** [comment]
Even after changing from 'm' to 'M', the issue is not resolved.  We need to make changes in the code or use a different approach.

**Comment by vatsar** [comment]
I have used a different approach to code this problem after going through some of the recording sessions and practising a bit.
